@extends('layout.app')
@section('content')
<div class="contenedor">
	<p>ESTOS  RESULTADOS SON DESALENTADORES, SOLO EL 32 % DE LOS ESTUDIANTES DE ENSEÑANZA  MEDIA, LOGRAN O SUPERAN EL NIVEL   BÁSICO  A2.  NIVEL LOGRADO 3 DE 10 ESTUDIANTES. ESTE BAJO NIVEL DE INGLÉS  PREVIO  A LOS ESTUDIOS SUPERIORES,  SE VEN AFECTADOS POR EL CAMBIO DE METODOLOGÍA  Y TERMINAN TITULÁNDOSE   SIN HABLAR INGLÉS DE MANERA  EFECTIVA.</p>
</div>
@endsection