@extends('layout.app')
@section('content')
<div class="contenedor">
	<p>CON UNA FIRME CONVICCIÓN Y CONSCIENTES DE NUESTRA RESPONSABILIDAD SOCIAL, QUEREMOS  PONER AL ALCANCE  DE LA COMUNIDAD EN GENERAL, BENEFICIOS  PREFERENCIALES  CON     BECAS 100%  Y SUBVENCIONES  75%,  PARA  QUE  DE ESTA FORMA  LOS ESTUDIANTES SE COMUNIQUEN   UTILIZANDO EL IDIOMA INGLÉS  COMO UNA HERRAMIENTA ALTAMENTE COMPETITIVA, FUNDAMENTAL PARA GENERAR MÁS Y MEJORES OPORTUNIDADES.</p>
</div>
@endsection