@extends('layout.app')
@section('content')
<div class="contenedor">
<div class="mision-vision">
	<h1>Finalidad</h1>
<p>DURANTE 15 AÑOS, HEMOS DESARROLLADO DE MANERA EXITOSA  UN PROYECTO EDUCATIVO DE INGLÉS CONVERSACIONAL , “ADVANCE LEARNERS PROGRAM”  MEDIANTE EL CUAL HEMOS    COADYUVADO  A LOS  ESTUDIANTES  DE ESTABLECIMIENTOS  EDUCACIONALES, A MEJORAR DE MANERA PROGRESIVAS LAS HABILIDADES COMUNICATIVAS (SPEAKING Y LISTENING).</p>	
</div>
</div>
@endsection
